In [1]:
import pandas as pd

In [2]:
strava_df = pd.read_csv("../DataInput/Strava/activities.csv")
strava_df.head()

,Activity ID,Activity Date,Activity Name,Activity Type,Activity Description,Elapsed Time,Distance,Max Heart Rate,Relative Effort,Commute,...,Intensity,Average Grade Adjusted Pace,Timer Time,Total Cycles,Recovery,With Pet,Competition,Long Run,For a Cause,Media
0,3560035534,"3 Jun 2020, 19:41:27",Evening Run,Run,NaN,3434,5.42,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3580028155,"7 Jun 2020, 19:21:30",Evening Run,Run,NaN,3192,5.30,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3620485461,"15 Jun 2020, 19:40:57",Evening Run,Run,NaN,2854,5.23,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3625765530,"16 Jun 2020, 19:48:38",Evening Run,Run,NaN,2851,5.29,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3651044244,"21 Jun 2020, 19:18:14",Evening Run,Run,NaN,3792,6.57,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

subset of the columns

In [3]:
strava_df = strava_df[["Activity Date", "Activity Name", "Activity Type", "Distance", "Calories"]]

In [4]:
strava_df

,Activity Date,Activity Name,Activity Type,Distance,Calories
0,"3 Jun 2020, 19:41:27",Evening Run,Run,5.42,NaN
1,"7 Jun 2020, 19:21:30",Evening Run,Run,5.30,NaN
2,"15 Jun 2020, 19:40:57",Evening Run,Run,5.23,NaN
3,"16 Jun 2020, 19:48:38",Evening Run,Run,5.29,NaN
4,"21 Jun 2020, 19:18:14",Evening Run,Run,6.57,NaN
...,...,...,...,...,...
919,"14 Aug 2025, 19:22:19",Evening Run,Run,5.17,311.0
920,"15 Aug 2025, 13:03:31",Back and biceps,Weight Training,0.00,95.0
921,"15 Aug 2025, 18:20:14",Evening Run,Run,2.90,177.0
922,"16 Aug 2025, 12:20:53",Afternoon Weight Training,Weight Training,0.00,128.0
923,"17 Aug 2025, 12:48:21",Afternoon Weight Training,Weight Training,0.00,123.0

Here, calories marked as NaN are useful- they signify that an activity has occurred in that day, but the data is missing.
To help later on, lets add a column to identify if we have exercised that day

In [5]:
strava_df["Did Exercise"] = 1

Lets adjust activity date column into dd/mm/yyyy

In [6]:
activity_date = strava_df["Activity Date"].apply(lambda s: " ".join(s.split(" ")[:3]))
activity_date = activity_date.apply(lambda s: s[:-1])
activity_date = pd.to_datetime(activity_date)
activity_date.head()

0   2020-06-03
1   2020-06-07
2   2020-06-15
3   2020-06-16
4   2020-06-21
Name: Activity Date, dtype: datetime64[ns]

In [7]:
strava_df["Activity Date"] = activity_date
strava_df = strava_df.set_index("Activity Date")

Dateset should be cleaned, save to file

In [8]:
strava_df.to_csv("./CleanedData/Cleaned_Strava.csv")